services:
  caddy:
    # https://github.com/caddyserver/caddy-docker
    build: caddy
    networks:
      unifi:
    ports:
      # INTERFACE:HOST:CONTAINER/PROTOCOL
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - "caddy-config:/config"
      - "caddy-data:/data"
  unifi:
    # https://github.com/jacobalberty/unifi-docker
    image: jacobalberty/unifi:v10
    networks:
      unifi:
    ports:
      # INTERFACE:HOST:CONTAINER/PROTOCOL
      - "3478:3478/udp"
      - "8080:8080"
      - "8443:8443"
    restart: unless-stopped
    volumes:
      - "unifi-data:/unifi/data"
networks:
  unifi:
volumes:
  caddy-config:
  caddy-data:
  unifi-data:
# vim: expandtab shiftwidth=2 tabstop=2
