services:
  caddy:
    # https://github.com/caddyserver/caddy-docker
    image: caddy:latest
    networks:
      unifi:
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - "./caddy/Caddyfile:/etc/caddy/Caddyfile"
      - "./http:/srv/http"
      - "caddy-config:/config"
      - "caddy-data:/data"
  unifi:
    # https://github.com/jacobalberty/unifi-docker
    image: jacobalberty/unifi
    networks:
      unifi:
    ports:
      - "3478:3478/udp"
      - "8080:8080"
      - "8443:8443"
    restart: unless-stopped
    volumes:
      - "unifi-data:/unifi/data"
networks:
  unifi:
volumes:
  caddy-config:
  caddy-data:
  unifi-data:
# vim: expandtab shiftwidth=2 tabstop=2
